const NEWS_FETCHING = "NEWS_FETCHING";
const NEWS_FETCHED = "NEWS_FETCHED";
const NEWS_FETCHED_ERROR = "NEWS_FETCHED_ERROR";
const NEWS_FETCH_UPDATE = "NEWS_FETCH_UPDATE";
const NEWS_FETCH_DELETE = "NEWS_FETCH_DELETE";
const FILTER_FETCHING = "FILTERED_FETCHING";
const FILTER_FETCHED = "FILTER_FETCHED";
const FILTERE_FETCH_ERROR = "FILTERE_FETCH_ERROR";
const ACTIVE_FILTER_CHANGED = "ACTIVE_FILTER_CHANGED";

export {
  NEWS_FETCHED,
  NEWS_FETCHED_ERROR,
  NEWS_FETCH_DELETE,
  NEWS_FETCH_UPDATE,
  NEWS_FETCHING,
  FILTER_FETCHING,
  FILTER_FETCHED,
  FILTERE_FETCH_ERROR,
  ACTIVE_FILTER_CHANGED,
};
